version: '3.3'
services:

  db:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/.env

  frontend:
    # image: reakfog/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    # image: reakfog/foodgram-backend:latest
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always 
    volumes: 
      - static_value:/code/static/ 
      - media_value:/code/media/ 
      - ../backend/:/code/
    depends_on: 
      - db 
    env_file: 
      - ../backend/.env

  nginx:
    image: nginx:1.19.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - backend 
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
